export const FETCH_DETAIL_STADIUM_BEGIN = 'FETCH_DETAIL_STADIUM_BEGIN';
export const FETCH_DETAIL_STADIUM_SUCCESS = 'FETCH_DETAIL_STADIUM_SUCCESS';
export const FETCH_DETAIL_STADIUM_FAILURE = 'FETCH_DETAIL_STADIUM_FAILURE';
export const FETCH_DETAIL_STADIUM_FAILURE_TEXT = 'Server đang bảo trì !'
