export const FETCH_USER_DETAIL_BEGIN = 'FETCH_USER_DETAIL_BEGIN';
export const FETCH_USER_DETAIL_SUCCESS = 'FETCH_USER_DETAIL_SUCCESS';
export const FETCH_USER_DETAIL_FAILURE = 'FETCH_USER_DETAIL_FAILURE';
