export const FETCH_LIST_USER_BEGIN = 'FETCH_LIST_USER_BEGIN';
export const FETCH_LIST_USER_SUCCESS = 'FETCH_LIST_USER_SUCCESS';
export const FETCH_LIST_USER_FAILURE = 'FETCH_LIST_USER_FAILURE';
export const FETCH_LIST_USER_FAILURE_TEXT = 'Server đang bảo trì !'