export const FETCH_LIST_TEAM_BEGIN = 'FETCH_LIST_TEAM_BEGIN';
export const FETCH_LIST_TEAM_SUCCESS = 'FETCH_LIST_TEAM_SUCCESS';
export const FETCH_LIST_TEAM_FAILURE = 'FETCH_LIST_TEAM_FAILURE';
export const FETCH_LIST_TEAM_FAILURE_TEXT = 'FETCH_LIST_TEAM_FAILURE_TEXT';