export const FETCH_LIST_STADIUM_BEGIN = 'FETCH_LIST_STADIUM_BEGIN';
export const FETCH_LIST_STADIUM_SUCCESS = 'FETCH_LIST_STADIUM_SUCCESS';
export const FETCH_LIST_STADIUM_FAILURE = 'FETCH_LIST_STADIUM_FAILURE';
export const FETCH_LIST_STADIUM_FAILURE_TEXT = 'Server đang bảo trì !'
